package com.testH.base.pages.client;

public abstract class PlayerProfilePage {
	
	public abstract void clickProfileBtn();
	public abstract void verifyProfileScreen();
	public abstract void verifyAchievementAndStatisticsTab();
	public abstract void verifyPlayerName();
	public abstract void verifyDepartment();
	public abstract void verifyLocation();
	public abstract void verifyActiveSince();
	public abstract void verifyRating(double rating);
	public abstract void verifyStatus();
	public abstract void verifyAndClickViewDownloadScoreCard();
	public abstract void verifyScoreCardPopup();
	public abstract void verifyWhatNextText();
	public abstract void verifyDownloadScoreCardText();
	public abstract void verifyShareOnSocialResumeText();
	public abstract void verifySocialIcons();
	public abstract void verifyDownloadButtonScorecard();
	public abstract void verifySuccessDownloadScorecard();
	public abstract void verifyAndClickCloseBtn();
	public abstract void verifyLevelImage();
	public abstract void verifyAndClickLevelShareIcon();
	public abstract void verifyMyLevelText();
	public abstract void verifyLevelNameImage();
	public abstract void verifyRookieAchieved();
	public abstract void verifyGameCountBeforePlaying(int gameRequiredForRookie,int gameRequiredForStarter,int gameRequiredForProfessional,int gameRequiredForAllStar,int gameRequiredForMaster);
	public abstract void verifyGameCountRookie(int totalGamePlayCount,int gameRequiredForRookie);
	public abstract void verifyGameCountStarter(int totalGamePlayCount,int gameRequiredForStarter);
	public abstract void verifyGameCountProfessional(int totalGamePlayCount,int gameRequiredForProfessional);
	public abstract void verifyGameCountAllStar(int totalGamePlayCount,int gameRequiredForAllStar);
	public abstract void verifyGameCountMaster(int totalGamePlayCount,String gameRequiredForMaster);
	public abstract void verifyMyAccomplishment();
	public abstract void verifyTrophiesField();
	public abstract void verifyContestField();
	public abstract void verifyRewardsField();
	public abstract void verifyMultilevelField();
	public abstract void verifyTrophyCountBubble(int expectedCount);
	public abstract void clickTrophies();
	public abstract void verifyTrophiesScreen();
	public abstract void clickContests();
	public abstract void verifyContestsScreen();
	public abstract void clickRewards();
	public abstract void verifyRewardsScreen();
	public abstract void clickMultilevel();
	public abstract void verifyMultilevelScreen();
	public abstract void verifyAndClickBackButton();
	public abstract void verifyFieldName(String expectedName);
	public abstract void verifyTrophyCount(int expectedTrophyCount);
	public abstract void verifyTrophyTitleSubTitle(String expectedTitle,String expectedSubtitle);
	public abstract void closeTrophyPopup();
	public abstract void selectTrophy(int trophyNum);
	public abstract void openSingleLevelGameTrophy();
	public abstract void verifyTrophyTitle(String expectedTitle);
	public abstract void verifyGameTrophyName();
	public abstract void verifyTotalPoints();
	public abstract void verifyAttempts();
	public abstract void verifyHighScore();
	public abstract void selectTab(String tabName);
	public abstract void verifyStatisticsTabOpening();
	public abstract void verifyLifeTimeTab();
	public abstract void verifyThisYearTab();
	public abstract void verifyThisMonthTab();
	public abstract void verifyLastMonthTab();
	public abstract void verifyStatisticsField(String expectedText);
	public abstract void verifyTotalPointsStatistics(int gamePoints);
	public abstract void verifyGamesCountStatistics(int gameCount);
	public abstract void verifyTrophiesCountStatistics(int TrophiesCount);
	public abstract void verifyPerfectGamesCountStatistics(int perfectGameCount);
	public abstract void verifyContestWonCountStatistics(int contestWonCount);
	public abstract void verifyTimePlayedCountStatistics();
	public abstract void verifyTimePlayedCountLastMonthStatistics();
	public abstract void verifyCurrentTab(String expectedText);
	public abstract void verifyLifetimeTab(String expectedText);
	public abstract void verifyPlayerLevelText(String expectedText);
    public abstract void verifyWeeklyStreakContainer();
    public abstract void verifyWeeklyStreakCount();
	

}
